name: pfe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  buttons_tabbar: ^1.3.8
  cached_network_image: ^3.3.1
  contained_tab_bar_view: ^0.8.0
  firebase_core: ^2.27.0
  firebase_database: ^10.4.9
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.2.0
  flutter_svg: ^2.0.10+1
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.8
  multi_image_picker_view: ^1.0.0
  flutter_native_image: ^0.0.6+1
  firebase_auth: ^4.17.8
  intl: ^0.19.0
  flutter_native_splash: ^2.3.10
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_email_sender: ^6.0.3
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png

flutter:
  assets:
    - assets/images/
  uses-material-design: true
